### ISSUE TITLE
Preferred way to use fix and scan in pre-commit hook

### ISSUE THREAD

**Issue by afuetterer** [jackdewinter/pymarkdown#1027]
Hi there,

I am a new user of this library. Maybe I have overlooked anything in the docs?

Is there a recommended way to use `fix` and `scan` in a pre-commit hook?

I would like to fix everything that is fixable and then run scan to show violations that needs to be handled manually.

Any help or pointers to the docs would be appreciated.

**Comment by jackdewinter** [comment]
you closed this.. however, I am working on some documentation this weekend for how to start the linter, and it will cover that.   Based on your feedback, I will make sure to have a good pointer to the docs for new users.

**Comment by afuetterer** [comment]
Thanks, I will give feedback, if I can.
You want to re-open this?
