### ISSUE TITLE
twine package in Pipfile

### ISSUE THREAD

**Issue by jkylekelly** [jackdewinter/pymarkdown#1258]
I’m researching unused software dependencies in lockfiles and came across your 2020 blog post: [Python Projects Using Pipenv](https://jackdewinter.github.io/2020/08/14/python-projects-using-pipenv/).

I noticed that twine is listed as a default package in the Pipfile. I’d recommend moving it to the dev packages since it’s typically not needed in production. Normally, I wouldn’t mention this, but as it seems to be the only non-production package included, I thought I'd make a note :)

**Comment by jackdewinter** [comment]
fixed... thanks for pointing this out.
