### ISSUE TITLE
bug: MD022 for whitespace around pyml comments

### ISSUE THREAD

**Issue by cpswan** [jackdewinter/pymarkdown#1268]
## Prerequisites

- [x] Are you running the latest version of this application?
- [x] Have you checked the [Frequently Asked Questions](https://pymarkdown.readthedocs.io/en/latest/faq) document?
- [x] Have you simplified the bug report to the essential details?
  - [x] Do you have a distinct command line to report?
  - [x] Can you clearly state the configuration for this bug report?
  - [x] Do you have a minimal document that highlights this bug?
  - [x] Are any required files (configuration or Markdown document) attached to the issue?
- [x] Did you perform a cursory search of other issues to look for related issues?

## Bug Report

Opening a separate issue as requested by @jackdewinter at https://github.com/jackdewinter/pymarkdown/issues/1208#issuecomment-2492765043

### Bug Type

- [ ] Assertion Failure
- [ ] Documentation
- [x] Scan/Rule not working as expected
- [ ] Fix/Rule not working as expected
- [ ] Other

### Description

A pyml comment isn't recognised as a not empty line for the purpose of MD022. Instead the comment line isn't counted, and so any empty line after it is seen as an additional contiguous empty line.

So a fragment like:

```markdown
## My header

<!-- pyml disable-num-lines 3 md011,md013-->

Some long lines
```

Lead to: `MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 2; Below] (blanks-around-headings,blanks-around-headers)`

### Specifics

What operating system and version are you running into this behavior on?

Ubuntu 24.04.1

What version are you seeing this behavior in? (Run `pip list` or `pipenv run pip list` and look for the entry beside `pymarkdownlnt`.)

0.9.25

Are there any extra steps that need to be taken before executing the application?

No

What is the command line you invoke to get this behavior?

`paymarkdown scan filename.md`

Are you using a configuration file? Either on the command line or one of the implicit configuration files? If so, attach that file to this issue.

No

What Markdown document causes this behavior to manifest?  Attach that file to this issue.

```markdown
# My header

<!-- pyml disable-num-lines 3 md011,md013-->

Some long lines
```

### Actual Behavior

```log
filename.md:1:1: MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 2; Below] (blanks-around-headings,blanks-around-headers)
```

### Expected Behavior

Clean scan

**Comment by jackdewinter** [comment]
this should be fixed in last nights release.  can you confirm?

**Comment by cpswan** [comment]
Thanks @jackdewinter I'm happy to confirm that things are now working ask expected with 0.9.26 :)
