### ISSUE TITLE
BadTokenizationError

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/pymarkdown#153]
I get a hard error on the document attached, when I run `pymarkdown scan docs_as_code.md`:

```
BadTokenizationError encountered while scanning 'docs_as_code.md':
An unhandled error occurred processing the document.
```

I have narrowed it down to the numbered list containing bullet point lists.

[docs_as_code_intro.md](https://github.com/jackdewinter/pymarkdown/files/7598465/docs_as_code_intro.md)

Markdownlint doesn't complain on this so I wonder what's going wrong here.

**Comment by jackdewinter** [comment]
In the middle of looking at another issue, will get to this one right after, as well as your other request.

**Comment by jackdewinter** [comment]
This is now fixed in the main branch.  How do you consume the project? Let me know and I will make sure you can test it out.

**Comment by jackdewinter** [comment]
I am doing a retrofit of whitespace logic right now, and plan to release a build when that is finished.

Hopefully... that is later this week.  Unless I hit a couple of roadblocks, I should be able to hit it!
________________________________
