### ISSUE TITLE
heading-style "consistent" does not select setext_with_atx

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/pymarkdown#154]
Hi @jackdewinter , I tried pymarkdownlint on a project where people use either setext_with_atx or atx style.

**Config:**

```
{
        "md003": {
            "style" : "consistent"
        }
}
```

**Problem:**

On this document, I get a warning `md003 " Heading style should be consistent throughout the document. [Expected: setext; Actual: atx] (heading-style,header-style)"`:

```md
Title
=====

Section 1
---------

### Subsection

Some text...
```

markdownlint has the same issue, but my point here is:

I would be very glad if rule md003 would detect the setext_with_atx style, because there is simply no other way to have headings of level 3 and below than with ATX (unlike in restructuredText).

Implementation is probably simple: If you encounter setext, just ignore headings L3+ (it can only be ATX, after all), or switch to setext_with_atx the first time the parser encounters a L3 ATX heading.

**Comment by jackdewinter** [comment]
@arwedus  Sorry it took me so long to get to this.
```
{"plugins": {"md003": {"allow-setext-update": True}}}
```
I just added a new setting for rule Md003, `allow-setext-update` which does what you have asked for.

**Comment by arwedus** [comment]
@jackdewinter: Sorry, been a while. Just wanted to say thanks a lot for implementing what I requested! I'll give it a try right now.
