### ISSUE TITLE
False MD033 positive for HTML end tags

### ISSUE THREAD

**Issue by scop** [jackdewinter/pymarkdown#22]
```shellsession
$ cat t.md
# <foo></foo>
$ pymarkdown scan t.md
t.md:1:3: MD033: Inline HTML [Element: foo] (no-inline-html)
t.md:1:8: MD033: Inline HTML [Element: ] (no-inline-html)
```

I think the latter ("`[Element: ]`") should not be emitted.

**Comment by Freed-Wu** [comment]
I met the similar thing:

I use python-md_toc to generate Table of Contents:

```
# title

<!--TOC-->

- [title](#title)

<!--TOC-->
```

However, pymarkdown will
```
README.md:3:1: MD033: Inline HTML [Element: !--TOC--] (no-inline-html)
README.md:7:1: MD033: Inline HTML [Element: !--TOC--] (no-inline-html)
```

It is weird, I think.

**Comment by jackdewinter** [comment]
Adjusted so that it doesn't trigger on end tags or tags that start with ! or ?

**Comment by jackdewinter** [comment]
Fixed: https://github.com/jackdewinter/pymarkdown/commit/fcd81a9aed148ec31890588fbafb1e4d8b2a1efb
