### ISSUE TITLE
[question] MD032 is weird

### ISSUE THREAD

**Issue by Freed-Wu** [jackdewinter/pymarkdown#27]
e.g.,

1.md:

```
# title

- 1
  - 1.1
    - 1.1.1
  - 1.2
- 2
```

2.md

```
# title

- 1
  - 1.1
    - 1.1.1

- 2
```

3.md

```
# title

- 1
  - 1.1
    - 1.1.1
- 2
```

However, 1.md and 2.md will pass the check of pymarkdown, 3.md will fail:

```
-1:0: MD032: Lists should be surrounded by blank lines (blanks-around-lists)
```

Is it right behavior?

**Comment by jackdewinter** [comment]
https://github.com/jackdewinter/pymarkdown/commit/be802c65b78e05f84b152f2f889658bcc226a32b
