### ISSUE TITLE
Unordered list inside ordered list, off by one?

### ISSUE THREAD

**Issue by gitpushdashf** [jackdewinter/pymarkdown#301]
Hi!

This seems a bit strange to me.

```
$ cat test.md
# Demo markdown

- Item
    - Sub item

1. Ordered item
    - Sub unordered item
$ pipx run pymarkdownlnt --set=plugins.md007.indent='$#4' --strict-config scan test.md
test.md:7:5: MD007: Unordered list indentation [Expected: 4, Actual=5] (ul-indent)
```

`Sub item` and `Sub unordered item` both have four spaces before the `-`. Is this right?

Thank you!

**Comment by jackdewinter** [comment]
Sorry for the delay in getting back to you.  Life happened.  I'll look into this tomorrow.  From what I remember, this is to support parsers like PyMarkdown which only recognize indents of 4 characters.
