### ISSUE TITLE
per-line ignore for line-length

### ISSUE THREAD

**Issue by fleimgruber** [jackdewinter/pymarkdown#373]
Given an error such as

```
README.md:26:1: MD013: Line length [Expected: 80, Actual: 152] (line-length)
```

is it possible to have the line-length rule ignored for that specific line (or code listing this line is part of)? I am thinking along the lines of `# noqa` for flake8 or `# pylint: disable=global-statement` for pylint. For comments in Markdown files I found https://stackoverflow.com/a/20885980.

What are your thoughts on this?

**Comment by jackdewinter** [comment]
Sorry for taking so long to get back to you, it's been a busy May so far.

Check out [Pragmas](https://github.com/jackdewinter/pymarkdown/blob/main/docs/advanced_scanning.md#pragmas)

**Comment by jackdewinter** [comment]
Did that link help at all?

**Comment by fleimgruber** [comment]
Now it is my turn: Sorry for taking so long to get back to you.

Thanks for the link and for writing up the comprehensive reasoning! FWIW, I fully agree with keeping things simple in the case of https://github.com/jackdewinter/pymarkdown/blob/main/docs/advanced_scanning.md#why-not-allow-disabling-for-more-than-one-line.

Keep up the good work, much appreciated!
