### ISSUE TITLE
Bug: false positive of warning ul-start-left in nested lists

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/pymarkdown#478]
**Problem:**

With the attached markdown file and pymarkdown config, the following warnings are issued:

~~~
$ pymarkdown --config pymarkdown.json.txt scan pymarkdown_md006_false_positive_example.md 
pymarkdown_md006_false_positive_example.md:21:3: MD006: Consider starting bulleted lists at the beginning of the line (ul-start-left)
pymarkdown_md006_false_positive_example.md:22:3: MD006: Consider starting bulleted lists at the beginning of the line (ul-start-left)
pymarkdown_md006_false_positive_example.md:23:3: MD006: Consider starting bulleted lists at the beginning of the line (ul-start-left)
~~~

[pymarkdown_md006_false_positive_example.md](https://github.com/jackdewinter/pymarkdown/files/9576162/pymarkdown_md006_false_positive_example.md)

[pymarkdown.json.txt](https://github.com/jackdewinter/pymarkdown/files/9576168/pymarkdown.json.txt)

Tested with: `pymarkdownlnt==0.9.7` and the current main branch commit.

**Expected result:**

No warnings are issued, as the indentation of the outer unordered list item is inherited from the previous paragraph.

**Comment by jackdewinter** [comment]
Good catch.  This was actually a weird parsing error.  Added some extra tests cases, and will be releasing soon.

**Comment by jackdewinter** [comment]
Can you retry this with the new 0.9.9 and see if it fixes this issue for you?  According to what I see with the above information, this looks fixed to me.

**Comment by jackdewinter** [comment]
Have not received any information in a month or so, and it looks like it is closed here.  Closing.

**Comment by arwedus** [comment]
@jackdewinter : Sorry for the long response time. I just ran pymarkdownlnt 0.9.9 on my example from the initial post again locally, and I get the same warnings:

```
str2lr@LE-Z12082:~/workspace/half-dome/athena_fus/src$ pymarkdown -c pymarkdown.json --strict-config scan ../pymarkdown_md006_false_positive_example.md 
../pymarkdown_md006_false_positive_example.md:21:3: MD006: Consider starting bulleted lists at the beginning of the line (ul-start-left)
../pymarkdown_md006_false_positive_example.md:22:3: MD006: Consider starting bulleted lists at the beginning of the line (ul-start-left)
../pymarkdown_md006_false_positive_example.md:23:3: MD006: Consider starting bulleted lists at the beginning of the line (ul-start-left)
```
