### ISSUE TITLE
linting: MD022 raised erroneously where references precede a heading

### ISSUE THREAD

**Issue by philandstuff** [jackdewinter/pymarkdown#541]
The following markdown file raises an MD022 warning:

```markdown
# Title

This is a [link][ref].

[ref]: https://github.com/jackdewinter/pymarkdown

## New heading
```

When I scan it, I get:

```
% pymarkdownlnt scan foo.md
foo.md:7:1: MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 2; Above] (blanks-around-headings,blanks-around-headers)
```

I do not expect this warning. The heading has only one blank line above it.

What I believe is happening is that the reference is being ignored somehow, and so pymarkdownlnt "sees" two blank lines immediately preceding the heading.

**Comment by jackdewinter** [comment]
a bit more nuanced, but yes, you hit got it!  LRDs are one of two of the blocks that do not have an end-token, so had to take care of that.  Fixed in https://github.com/jackdewinter/pymarkdown/commit/338da2e3a9422d16fc80481f39ad012f59b6f8a3 and hoping to do a release in the next couple of days.

**Comment by philandstuff** [comment]
Thank you! ❤️

**Comment by jackdewinter** [comment]
just released this afternoon... sorry for the delay.  wanted to clean some stuff up.  can you test it on your end just to make sure I did not miss something?

**Comment by philandstuff** [comment]
I’m afraid I’ve left the role where this affected me, but @munhitsu might be able to check

**Comment by munhitsu** [comment]
sweet it works - I've checked agains the main branch I'll certainly have a few md files to fix after you release it :)
