### ISSUE TITLE
List with fenced code blocks containing yaml with lists raise MD031

### ISSUE THREAD

**Issue by gionn** [jackdewinter/pymarkdown#626]
Looks really a super edge case, I get a `MD031` at the `resources` array inside the code block

Avoid using the outer ordered list make the error disappear.

It looks like it interprets the yaml array inside the fenced code block as it was a markdown list 😖 

Markdown code:

```
### Steps

1. First create the cluster configuration to link flux2 to a pipeline
   environment, create `clusters/my-cluster-name/apps.yaml` with the following code:

    ```yaml
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
        name: apps
        namespace: flux-system
    spec:
        interval: 2m0s
        sourceRef:
            kind: GitRepository
            name: flux-system
        path: ./apps/overlays/my-custom-overlay
        prune: true
        wait: true
        timeout: 1m
    ```

2. Create `./apps/overlays/my-custom-overlay/kustomization.yml` file, pointing
   to one or more `base` folder and override specific resources with
   `patchesStrategicMerge:` and a list of yaml files that will override the base
   config.

    ```yaml
    ---
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
        - ../../base/git-common
        - ../../base/git-acs
        - ../../base/git-aae
        - my-custom-resource.yml
    patchesStrategicMerge:
        - my-override-resource.yml
    ```
```

latest pymarkdown output:

```
README.md:131:4: MD031: Fenced code blocks should be surrounded by blank lines (blanks-around-fences)
README.md:131:9: MD004: Inconsistent Unordered List Start style [Expected: asterisk; Actual: dash] (ul-style)
README.md:131:9: MD007: Unordered list indentation [Expected: 4, Actual=9] (ul-indent)
README.md:132:9: MD007: Unordered list indentation [Expected: 4, Actual=9] (ul-indent)
README.md:133:9: MD007: Unordered list indentation [Expected: 4, Actual=9] (ul-indent)
README.md:134:9: MD007: Unordered list indentation [Expected: 4, Actual=9] (ul-indent)
README.md:136:5: MD032: Lists should be surrounded by blank lines (blanks-around-lists)
README.md:136:9: MD007: Unordered list indentation [Expected: 4, Actual=9] (ul-indent)
README.md:137:5: MD031: Fenced code blocks should be surrounded by blank lines (blanks-around-fences)
README.md:137:5: MD040: Fenced code blocks should have a language specified (fenced-code-language)
README.md:139:4: MD031: Fenced code blocks should be surrounded by blank lines (blanks-around-fences)
```

Cheers!

**Comment by jackdewinter** [comment]
This one is on the list for me to look at this weekend when I have some time. Stay tuned.

**Comment by jackdewinter** [comment]
This was just fixed with commit e2e6fc4457cf8126aaf4ff04f88cff776eed03ed .  Are you using pre-commit and can sync to that hash, or do you need to wait for a release to verify it?

(I verified that it was broken before that fix, and the new test passes.  However, I always prefer to have the person who reported it validate it if possible.)

**Comment by gionn** [comment]
Hello, thank you very much for looking into it!

Unfortunately I've troubles in verifying it:

```
PyMarkdown...............................................................Failed
- hook id: pymarkdown
- exit code: 1

Traceback (most recent call last):
  File "/Users/Giovanni.Toraldo/.cache/pre-commit/repo8sooshrj/py_env-python3/bin/pymarkdown", line 5, in <module>
    from pymarkdown.__main__ import main
  File "/Users/Giovanni.Toraldo/.cache/pre-commit/repo8sooshrj/py_env-python3/lib/python3.11/site-packages/pymarkdown/__init__.py", line 5, in <module>
    from pymarkdown.main import PyMarkdownLint  # noqa F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Giovanni.Toraldo/.cache/pre-commit/repo8sooshrj/py_env-python3/lib/python3.11/site-packages/pymarkdown/main.py", line 21, in <module>
    from pymarkdown.extension_manager.extension_manager import ExtensionManager
  File "/Users/Giovanni.Toraldo/.cache/pre-commit/repo8sooshrj/py_env-python3/lib/python3.11/site-packages/pymarkdown/extension_manager/extension_manager.py", line 21, in <module>
    from pymarkdown.extensions.front_matter_extension import FrontMatterExtension
  File "/Users/Giovanni.Toraldo/.cache/pre-commit/repo8sooshrj/py_env-python3/lib/python3.11/site-packages/pymarkdown/extensions/front_matter_extension.py", line 15, in <module>
    from pymarkdown.extensions.front_matter_markdown_token import FrontMatterMarkdownToken
  File "/Users/Giovanni.Toraldo/.cache/pre-commit/repo8sooshrj/py_env-python3/lib/python3.11/site-packages/pymarkdown/extensions/front_matter_markdown_token.py", line 7, in <module>
    from pymarkdown.leaf_markdown_token import LeafMarkdownToken
  File "/Users/Giovanni.Toraldo/.cache/pre-commit/repo8sooshrj/py_env-python3/lib/python3.11/site-packages/pymarkdown/leaf_markdown_token.py", line 6, in <module>
    from pymarkdown.links.link_reference_info import LinkReferenceInfo
ModuleNotFoundError: No module named 'pymarkdown.links'
```

Previously was running fine:

```
   - repo: https://github.com/jackdewinter/pymarkdown
-    rev: v0.9.9
+    rev: e2e6fc4457cf8126aaf4ff04f88cff776eed03ed
    hooks:
      - id: pymarkdown
        files: (README\.md$|docs/.*\.md)
        args:
          - --config=.pymarkdown.json
          - scan
```

New issue or something that I am missing?

**Comment by jackdewinter** [comment]
Nope, something on my end.  Normally I only worry about the point releases, and I have some tests that I run that would have uncovered this.  Try using 98e2e65349d6bf842d4be1a877b1808baae9201b instead.  Fixed those issues on my end with that commit.

**Comment by gionn** [comment]
Everything green now!

Thank you very much.
