### ISSUE TITLE
Robustness: BadTokenizationError when parsing document with linebreak in link text

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/pymarkdown#634]
## Problem description

When running pymarkdown on the following document, I get the error "BadTokenizationError":

```md
## Variational Gaussian mixture models

The theory of VGM shouldn't be explained in detail here.
Following prior distributions are needed to calculate a VGM with its respective posteriors:

1. Dirichlet distribution: for categorical distribution of weights
   * prior weight concentration parameter
2. Normal-Wishart distribution: for multivariate normal distributions
   * expected mean
   * scaling factor for covariance of mean (\> 0)
   * scale matrix of Wishart distribution (must be positive definite like the covariance matrix)
   * degrees of freedom of Wishart distribution

Further literature:

1.  [Scikit-learn: Machine Learning in {P}ython} - Gaussian mixture
    models](https://scikit-learn.org/stable/modules/mixture.html)
2.  [Bishop - Pattern Recognition and Machine Learning,
    p. 474ff.](http://users.isr.ist.utl.pt/~wurmd/Livros/school/Bishop%20-%20Pattern%20Recognition%20And%20Machine%20Learning%20-%20Springer%20%202006.pdf)
```

If the line break in the link texts in line 16 and 18 are removed, the document is parsed successfully by pymarkdown.

Config file: [pymarkdown.json.txt](https://github.com/jackdewinter/pymarkdown/files/11077157/pymarkdown.json.txt)

## Expected behavior

While line breaks inside the markdown link text are not explicitly allowed in the CommonMark spec, they are also not explicitly forbidden and therefore, some renderers like the VS Code markdown preview support them. Github does so, too:

[Scikit-learn: Machine Learning in {P}ython} - Gaussian mixture
models](https://scikit-learn.org/stable/modules/mixture.html)

Therefore, pymarkdownlnt shall not abort on such cases as the one above, but rather issue a warning instead.

## Version Info

pymarkdownlnt==0.9.9
OS = Ubuntu Linux 20.04
Python=3.8.10

**Comment by jackdewinter** [comment]
Fixed, will be releasing a new version soon.

**Comment by jackdewinter** [comment]
Released 0.9.10 last weekend that should fix this. Can you confirm?

**Comment by jackdewinter** [comment]
closing after no response

**Comment by arwedus** [comment]
fix confirmed on original file, thanks :)
