### ISSUE TITLE
Pre-commit CI doesn't autoupdate pymarkdown?

### ISSUE THREAD

**Issue by vunhatchuong** [jackdewinter/pymarkdown#685]
So I have https://pre-commit.ci/ in my repo, which will detect version of pre-commit hooks and autoupdate them. For some reason it doesn't autoupdate pymarkdown.

**Comment by vunhatchuong** [comment]
I update manually and now pre-commit ci wants to downgrade it. https://github.com/vunhatchuong/python-setup-template/pull/7

**Comment by jackdewinter** [comment]
Just got back from time off, will be looking at this during the week.

**Comment by jackdewinter** [comment]
This is reproducible using `pipenv run pre-commit autoupdate`

It was a weird instance where the tag did not make it over to the `main` branch for some reason. It works here, so please verify that it works in your case.

**Comment by vunhatchuong** [comment]
Looks like it fixed
