### ISSUE TITLE
Example for how to use module inline with code

### ISSUE THREAD

**Issue by byrnereese** [jackdewinter/pymarkdown#690]
I want to create a mkdocs plugin (a markdown-based documentation system) that would invoke the linter for every file processed. To do this, I need to be able to invoke pymarkdown from within a code block. For example, is anything like this possible:

```
import PyMarkdownLint

linter = PyMarkdownLint()
results = linter.scan_file( "foo.md" )
results = linter.scan_string( "# Foo" )

**Comment by jackdewinter** [comment]
It turned into a project to provide a better API, and that is due out in the currently baking 0.9.12.  The documentation is [here](https://github.com/jackdewinter/pymarkdown/blob/main/docs/api-usage.md) for API Usage and [here](https://github.com/jackdewinter/pymarkdown/blob/main/docs/api.md) for auto-generated docs.

If you could look over those files and give me constructive input, that would be great!

**Comment by jackdewinter** [comment]
closing as no further comments have been provided
