### ISSUE TITLE
How to add own extension

### ISSUE THREAD

**Issue by trunneml** [jackdewinter/pymarkdown#697]
Hi,

How can I activate and implement my own extension?

Background:

I'm trying to collect all processed headers and assets in a JSON file. I have already implemented some rules, which were straightforward. However, I'm unclear about how to implement and activate an extension. Could you give me some advice?

**Comment by jackdewinter** [comment]
Can you give me some idea of what you have worked on, what it looks like, etc.?  While I have those extension points in the project, you will be the first person to use them outside of the project, so some birthing pains might occur.

**Comment by jackdewinter** [comment]
That is what I would recommend as well.  Is the mechanism for adding a plugin working properly for you?
