### ISSUE TITLE
Mismatch between package in PyPi and repo

### ISSUE THREAD

**Issue by gsalvatella** [jackdewinter/pymarkdown#698]
There seems to be a mismatch between the contents of the current package in the PyPi repository and the actual project:

```sh
python -m venv .venv && . .venv/bin/activate
pip install --upgrade pip && pip install pymarkdownlnt
pymarkdown version
0.9.11
cat .venv/lib/python3.x/site-packages/pymarkdown/main.py
```
For example, lines 43,44 containing the paths for the `pyproject.toml` are not present in the package's `main.py`.

**Comment by NiBa97** [comment]
Can confirm, really annoying at the `pyproject.toml` would be quite useful for my usecase.

**Comment by Bouni** [comment]
I ran into the same issue. After searching a bit I realized the support for config via `pyproject.toml` was merged on April 24th (#665) but the current version 0.9.10 was released on April 18th.
So I hope @jackdewinter will release a new version containing this feature very soon 😄

**Comment by gsalvatella** [comment]
> I ran into the same issue. After searching a bit I realized the support for config via `pyproject.toml` was merged on April 24th (#665) but the current version 0.9.10 was released on April 18th. So I hope @jackdewinter will release a new version containing this feature very soon 😄

The `v0.9.11` tag includes those changes in the code, so it should be present in the package according to its version. There is a mismatch there, it's not only a question of updating...

**Comment by jackdewinter** [comment]
I have a release candidate on my system, and doing extra checks on it before I release it.

**Comment by jackdewinter** [comment]
Hopefully this is taken care of with the new release process.  Please let me know if this is not the case.

**Comment by jackdewinter** [comment]
fixed as no more comments pending
