### ISSUE TITLE
Relax version constraints for dependencies

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/pymarkdown#708]
I can't use pymarkdownlnt any more, because it has a dependency on typing-extensions==4.4.0. Can you maybe create a pymarkdownlnt release that adds a more permissive dependency on typing-extensions, maybe >=4.4?

This used to work fine as long as pymarkdownlnt had the highest version demant, but now, I have another package in my requirements.in that requires typing-extensions >=4.6 via pydantic 2.0., and so I've got an unsolveable version conflict.

Probably applies to many other version dependencies as well. Ideally, the version constraints are as low as possible.

I've added a change proposal in a pull request.

**Comment by jackdewinter** [comment]
This has been addressed in the latest changes for the 0.9.12 release, which is just baking until I have some time to do some final checks.

**Comment by jackdewinter** [comment]
fixed as having no further comments
