### ISSUE TITLE
Add support for returning 0 on successful execution (with or without findings)

### ISSUE THREAD

**Issue by aasmundbo** [jackdewinter/pymarkdown#744]
Reported based on using `pymarkdown`  0.9.12.

Today, `pymarkdown` returns 
1. 0 on successful execution when there are no findings
2. Non-zero on successful execution when there are findings
3. Non-zero on error, for example if there is e.g. configuration errors (e.g. when using `mode.strict-config`)

Please consider changing so that scenario 2 above also returns 0, or that you add a configuration option to return 0 in that case (for example `--zero-on-success` or `--success-code 0`).

Background: I want to run pymarkdown from `subprocess.check_call()` which raises exceptions for all non-zero return codes.

**Comment by jackdewinter** [comment]
Decided to go in a slightly different direction with the `--return-code-scheme` argument.  Let me know if that works for you.

**Comment by aasmundbo** [comment]
v0.9.13 crashes for me:
```
$ pymarkdownlnt -h
Traceback (most recent call last):
  File "/home/a0132611/.local/bin/pymarkdownlnt", line 5, in <module>
    from pymarkdown.__main__ import main
  File "/home/a0132611/.local/lib/python3.8/site-packages/pymarkdown/__init__.py", line 5, in <module>
    from pymarkdown.main import PyMarkdownLint  # noqa F401
  File "/home/a0132611/.local/lib/python3.8/site-packages/pymarkdown/main.py", line 22, in <module>
    from pymarkdown.extension_manager.extension_manager import ExtensionManager
  File "/home/a0132611/.local/lib/python3.8/site-packages/pymarkdown/extension_manager/extension_manager.py", line 20, in <module>
    from pymarkdown.extensions.front_matter_extension import FrontMatterExtension
  File "/home/a0132611/.local/lib/python3.8/site-packages/pymarkdown/extensions/front_matter_extension.py", line 15, in <module>
    from pymarkdown.extensions.front_matter_markdown_token import FrontMatterMarkdownToken
  File "/home/a0132611/.local/lib/python3.8/site-packages/pymarkdown/extensions/front_matter_markdown_token.py", line 7, in <module>
    from pymarkdown.general.parser_helper import ParserHelper
ModuleNotFoundError: No module named 'pymarkdown.general'
```

Reverting back to v0.9.12 with `pip install pymarkdownlnt==0.9.12` and it works again.

**Comment by jackdewinter** [comment]
Try https://github.com/jackdewinter/pymarkdown/releases/tag/v0.9.13.4

**Comment by aasmundbo** [comment]
Tested 0.9.13.4 and I'm happy with the solution 👍 
Not sure about the flow here, but I'm OK with closing this ticket.

**Comment by jackdewinter** [comment]
"not sure about the flow here"?

**Comment by aasmundbo** [comment]
My apologies for not being clear. The “not sure about the flow” was related to whether I should close the ticket or someone else (I see the “close with comment” option)
