### ISSUE TITLE
Broken links on pypi README

### ISSUE THREAD

**Issue by alicederyn** [jackdewinter/pymarkdown#929]
On https://pypi.org/project/pymarkdownlnt/ in the "API Support" section, there are links to:

- https://pypi.org/project/pymarkdownlnt/docs/api.md
- https://pypi.org/project/pymarkdownlnt/docs/api-usage.md

I get a 404 page for both of these.

(There may be more broken links, I haven't checked :) )

**Comment by jackdewinter** [comment]
noted, and should be fixed with the next publish.

**Comment by jackdewinter** [comment]
release last night, should be fixed.

**Comment by jackdewinter** [comment]
closing due to lack of response

**Comment by alicederyn** [comment]
I confirm the links are working now, thanks.
