### ISSUE TITLE
Missing py.typed file in wheel

### ISSUE THREAD

**Issue by alicederyn** [jackdewinter/pymarkdown#930]
The pymarkdown API has type annotations, but the wheel is missing [a `py.typed` file](https://peps.python.org/pep-0561/#packaging-type-information), so type checkers like mypy are ignoring them.

> Skipping analyzing "pymarkdown.api": module is installed, but missing library stubs or py.typed marker ([import-untyped](https://mypy.readthedocs.io/en/stable/_refs.html#code-import-untyped))

This doesn't impact use much (just need to type-ignore the errors), but it would be great if one could be added!

**Comment by jackdewinter** [comment]
release last night, should be fixed.

**Comment by jackdewinter** [comment]
closing due to lack of response

**Comment by alicederyn** [comment]
Oh sorry! Didn't realise you were waiting for one! I haven't had a chance to check but the PR looks reasonable. Thanks!
