### ISSUE TITLE
[Feature] Continue scanning after unhandled errors

### ISSUE THREAD

**Issue by Bugzey** [jackdewinter/pymarkdown#946]
Hi, all.

Currently when scanning multiple documents the scan process exits immediately if it encounters an unhandled error. While we do need to fix errors either in the code or in the document, this stops us from handling linting issues in documents following the one that triggered the error. This could be avoided if broken files are ignored on error, scanning and linting continues to the end of all files and finally we get a list of files with unhandled errors.

This would work similarly to unit test frameworks - they record test failures or code errors but continue running all following tests.

Here is an example trio of files that will trigger the nasty behaviour, leaving `file 3.md` unchecked:

* File 1 - OK - [file 1.md](https://github.com/jackdewinter/pymarkdown/files/13843886/file.1.md)
* File 2 - Broken - [file 2.md](https://github.com/jackdewinter/pymarkdown/files/13843888/file.2.md)
* FIle 3 - OK - [file 3.md](https://github.com/jackdewinter/pymarkdown/files/13843894/file.3.md)

Example expected output:

```
file 1.md:1:1: MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 0; Below] (blanks-around-headings,blanks-around-headers)
file 1.md:1:2: MD010: Hard tabs [Column: 2] (no-hard-tabs)
file 1.md:3:1: MD032: Lists should be surrounded by blank lines (blanks-around-lists)
file 3.md:1:1: MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 0; Below] (blanks-around-headings,blanks-around-headers)
file 3.md:1:2: MD010: Hard tabs [Column: 2] (no-hard-tabs)
file 3.md:3:1: MD032: Lists should be surrounded by blank lines (blanks-around-lists)

Unhandled exceptions caught when processing files:
file 2.md
```

Actual output:

```
file 1.md:1:1: MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 0; Below] (blanks-around-headings,blanks-around-headers)
file 1.md:1:2: MD010: Hard tabs [Column: 2] (no-hard-tabs)
file 1.md:3:1: MD032: Lists should be surrounded by blank lines (blanks-around-lists)


Unexpected Error(BadTokenizationError): An unhandled error occurred processing the document.
```

Thank you for your attention!

Best wishes,
Bugzey

**Comment by jackdewinter** [comment]
like the idea... give me a bit to think on how to make it look "right"

**Comment by jackdewinter** [comment]
closing due to lack of response
