### ISSUE TITLE
Wrong no-multiple-space-atx warning if atx heading is followed by a badly shaped <pre>-block

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/pymarkdown#977]
# Overview

This is an example for using `<pre>` tag instead of markdown code blocks notation.
No idea why someone would do it but it leads to an error in pymarkdown parsing.
It's a rare case and I think that the fact that we stumble upon such edge cases is a good sign showing the overall quality of pymarkdown, so thanks for that 👍🏼 .

## Setup

Installed python packages:

<pre>
application_properties==0.8.2
pymarkdownlnt==0.9.16
pyyaml==5.4.1.post0  # constraint
</pre>

Command line:

<pre>
pymarkdown -c pymarkdown.json scan readme.md
</pre>

The file that causes the error:

[readme.md](https://github.com/jackdewinter/pymarkdown/files/14123399/readme.md)

The error message is:

```
readme.md:29:1: MD019: Multiple spaces are present after hash character on Atx Heading. (no-multiple-space-atx)
```

## Config

<pre>
{
    "mode" : {
        "strict_config" : true
    },
    "extensions" : {
        "front-matter" : {
            "enabled" : true
        }
    },
    "plugins" : {
        "md002": {
            "enabled" : false
        },
        "md003": {
            "enabled" : true,
            "style" : "consistent",
            "allow-setext-update" : true
        },
        "md004": {
            "enabled" : false,
            "style": "sublist"
        },
        "md006": {
            "enabled" : true
        },
        "md007": {
            "enabled" : false
        },
        "md012": {
            "maximum": 2
        },
        "md013": {
            "enabled" : true,
            "line_length": 1000,
            "heading_line_length": 120,
            "code_block_line_length": 160
        },
        "md022" : {
            "lines_above": 1,
            "lines_below": 1
        },
        "md024" : {
            "enabled" : false
        },
        "md030": {
            "enabled" : false
        },
        "md033": {
            "enabled" : false
        },
        "md034": {
            "enabled" : false
        },
        "md036": {
            "enabled" : false
        },
        "md037": {
            "enabled" : false
        },
        "md040": {
            "enabled" : false
        },
        "md041": {
            "enabled" : false
        },
        "md045": {
            "enabled" : false
        },
        "code-block-style" : {
            "enabled" : false
        },
        "no-alt-text" : {
            "enabled" : false
        }
    }
}
</pre>

## steps to reproduce

<pre>
python -m virtualenv .venv
source .venv/bin/activate
pip install -r requirements.txt
pymarkdown -c pymarkdown.json scan readme.md
</pre>

**Comment by jackdewinter** [comment]
will be in the next release.

**Comment by jackdewinter** [comment]
closed after no response.
